name: Validate action typings

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate-typings:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: krzema12/github-actions-typing@00bdd654abadab98ae7076697f91bb722fd63666 # v0.7.0
